### ISSUE TITLE
sdf or SQL script

### ISSUE THREAD

**Issue by tancm** [tjbranch80/PawnPOS#1]
Hi TJ

Where can i get the sdf file or SQL Script

**Comment by tjbranch80** [comment]
Right now the project has not been completed. I will try to upload the rest
as soon as I can. Are you interested in this type of software?

**Comment by tancm** [comment]
YES

**Comment by salahzidi** [comment]
Can you put the sdf database please?

**Comment by tjbranch80** [comment]
I have not worked on this project for a while. I will look for it today.

**Comment by salahzidi** [comment]
Do a favor and send it to me to slh.zidi@gmail.com
Thanks in advance :)

**Comment by tjbranch80** [comment]
I just uploaded it. Not sure what state it is in, it has been a long while
since I have worked on it.

**Comment by salahzidi** [comment]
Thank a lot !
